//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkDays.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class bts_projectroles
    {
        public int id { get; set; }
        public string name { get; set; }
        public System.DateTime date_from { get; set; }
        public System.DateTime date_to { get; set; }
        public string project { get; set; }
        public string group_name { get; set; }
        public string role { get; set; }
        public string agreement_type { get; set; }
        public string role_agreement { get; set; }
        public string agreement_company { get; set; }
    }
}
