//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkDays.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class worklog
    {
        public int ID { get; set; }
        public Nullable<int> issueid { get; set; }
        public string AUTHOR { get; set; }
        public string grouplevel { get; set; }
        public string rolelevel { get; set; }
        public string worklogbody { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string UPDATEAUTHOR { get; set; }
        public Nullable<System.DateTime> UPDATED { get; set; }
        public Nullable<System.DateTime> STARTDATE { get; set; }
        public Nullable<int> timeworked { get; set; }
    }
}
