//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkDays.Tests.IntegrationTests
{
    using System;
    using System.Collections.Generic;
    
    public partial class worklog:WorkDays.Domain.worklog
    {
        public new int ID { get; set; }
        public new Nullable<decimal> issueid { get; set; }
        public new string AUTHOR { get; set; }
        public new Nullable<System.DateTime> STARTDATE { get; set; }
    }
}
